[package]
name = "journal"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.5"
dirs = "4.0.0"
figment = { version = "0.10.6", features = ["test", "env", "yaml"] }
pulldown-cmark = { version = "0.8.0" }
pulldown-cmark-to-cmark = { version = "7.1.0" }
regex = { version = "1.5" }
serde = { version = "1.0.130", features = ["derive" ] }
tera = { version = "1", default-features = false }
time = { version = "0.3.5", features = ["std", "formatting"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.2.0"

[dev-dependencies]
assert_fs = "1.0"
data-test = "0.1.0"
indoc = "1.0"
predicates = "2.1.0"
tracing-test = "0.2.1"
